# -*- coding: utf-8 -*-
"""c1142.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WlFSw8xKsOweIzXjbIwT8U6tSJhZWQpj
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px

df=pd.read_csv("main2.csv")
TOEFL_Score=df["TOEFL Score"].tolist()
Chances_of_admit=df["Chance of Admit "].tolist()
fig=px.scatter(x=TOEFL_Score,y=Chances_of_admit)
fig.show()

m = 1
c = 0
y = []
for x in TOEFL_Score:
  y_value = m*x + c
  y.append(y_value)

#Plotting the points
fig = px.scatter(x=TOEFL_Score, y=Chances_of_admit)
fig.update_layout(shapes=[
    dict(
      type= 'line',
      y0= min(y), y1= max(y),
      x0= min(TOEFL_Score), x1= max(TOEFL_Score)
    )
])
fig.show()

x = 600
y = m * x + c
print(f"Chances of admit of someone based on their TOEFL Score {x} is {y}")